name: ubuntu

on: [push, pull_request]

jobs:
  build:
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, macos-10.15, windows-2019 ]
        ruby: [ '3.0', 2.7, 2.6, head ]
        include:
          - { os: windows-2019 , ruby: mingw }
          - { os: windows-2019 , ruby: mswin }
        exclude:
          - { os: windows-2019 , ruby: head }
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run test
      run: rake test
